### ISSUE TITLE
Question about synthetic dataset

### ISSUE THREAD

**Issue by YanhaoZhang** [JiaxiongQ/NeuS-HSR#7]
Hi, Thanks a lot for releasing the code. A quick question about the synthetic dataset. It seems that the reflection part is not consistent with the transmission image. For example, in the following two images, the area of the reflection part seems not to be the same. I am a bit confused. May I ask when creating the synthetic data, is a glass plane used to generate the reflection image? 

![000002](https://github.com/user-attachments/assets/eed1aa5c-9920-43d0-8db6-26279e707fd8)
![000003](https://github.com/user-attachments/assets/8642c1f4-ce9b-4d39-abca-30a9c522224f)

**Comment by JiaxiongQ** [comment]
Thanks for your interest. We consider that the reflection object might be
dynamic, and then we randomly select the reflection image in a scene.

**Comment by YanhaoZhang** [comment]
Hi @JiaxiongQ Thanks a lot for your prompt reply. I now understand it.
